[package]
name = "pmortem"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"

[target.'cfg(target_os = "macos")'.dependencies]
libc = "0.2.167"
mach2 = "0.4.2"
